# Generated by Django 4.1 on 2022-09-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_tag_order_customer_order_product_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="note",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
